In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv

In [2]:
import pandas as pd
train_df = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/train.csv')
print(train_df.shape)
train_df.head()

(1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
test_df = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/test.csv')
print(test_df.shape)
test_df.head()

(1459, 80)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [4]:
train_df['SalePrice'].mean()

180921.19589041095

In [7]:
test_df['SalePrice'] = pd.Series([train_df['SalePrice'].mean()]*len(train_df))
test_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,180921.19589
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,180921.19589
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,180921.19589
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,180921.19589
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,180921.19589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,180921.19589
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,180921.19589
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,180921.19589
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,180921.19589
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,180921.19589

In [8]:
test_df[['Id','SalePrice']].to_csv('Average_Prediction.csv', index = False)

In [9]:
import copy
train_df_sub = copy.deepcopy(train_df[['MSSubClass', 'LotFrontage', 'SalePrice']])
train_df_sub = train_df_sub.fillna(train_df_sub.mean())
train_df_sub

      MSSubClass  LotFrontage  SalePrice
0             60         65.0     208500
1             20         80.0     181500
2             60         68.0     223500
3             70         60.0     140000
4             60         84.0     250000
...          ...          ...        ...
1455          60         62.0     175000
1456          20         85.0     210000
1457          70         66.0     266500
1458          20         68.0     142125
1459          20         75.0     147500

[1460 rows x 3 columns]

In [11]:
x_train, y_train = train_df_sub.to_numpy()[:,:-1], train_df_sub.to_numpy()[:,-1]
y_train

array([208500., 181500., 223500., ..., 266500., 142125., 147500.])

In [12]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression().fit(x_train, y_train)
lr

LinearRegression()

In [13]:
lr.coef_

array([  75.96942776, 1260.11397803])

In [14]:
lr.intercept_

88327.8118861935

In [15]:
train_df_sub['linear-prediction'] = lr.predict(x_train)
train_df_sub

      MSSubClass  LotFrontage  SalePrice  linear-prediction
0             60         65.0     208500      174793.386124
1             20         80.0     181500      190656.318684
2             60         68.0     223500      178573.728058
3             70         60.0     140000      169252.510511
4             60         84.0     250000      198735.551706
...          ...          ...        ...                ...
1455          60         62.0     175000      171013.044190
1456          20         85.0     210000      196956.888574
1457          70         66.0     266500      176813.194379
1458          20         68.0     142125      175534.950948
1459          20         75.0     147500      184355.748794

[1460 rows x 4 columns]

In [16]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(train_df_sub['SalePrice'], train_df_sub['linear-prediction'])

54381.25047406032

In [17]:
test_df_sub = copy.deepcopy(test_df[['MSSubClass', 'LotFrontage']])
test_df_sub

      MSSubClass  LotFrontage
0             20         80.0
1             20         81.0
2             60         74.0
3             60         78.0
4            120         43.0
...          ...          ...
1454         160         21.0
1455         160         21.0
1456          20        160.0
1457          85         62.0
1458          60         74.0

[1459 rows x 2 columns]

In [18]:
test_df_sub = test_df_sub.fillna(test_df_sub.mean())
test_df_sub

      MSSubClass  LotFrontage
0             20         80.0
1             20         81.0
2             60         74.0
3             60         78.0
4            120         43.0
...          ...          ...
1454         160         21.0
1455         160         21.0
1456          20        160.0
1457          85         62.0
1458          60         74.0

[1459 rows x 2 columns]

In [19]:
x_test = test_df_sub.to_numpy()
x_test

array([[ 20.,  80.],
       [ 20.,  81.],
       [ 60.,  74.],
       ...,
       [ 20., 160.],
       [ 85.,  62.],
       [ 60.,  74.]])

In [20]:
test_df['SalePrice'] = lr.predict(x_test)
test_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,190656.318684
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,191916.432662
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,186134.411926
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,191174.867838
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,151629.044272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,126945.313866
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,126945.313866
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,291465.436927
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,172912.279884
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,186134.411926

In [21]:
test_df[['Id','SalePrice']].to_csv('Linear_Prediction.csv', index = False)